"""LangGraph multi-agent workflow."""

from __future__ import annotations

import json
from typing import Any, Literal

from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, StateGraph

from backend.agents.llm import get_llm

from backend.agents.prompts import (
    ANALYST_PROMPT,
    INSIGHT_PROMPT,
    ORCHESTRATOR_PROMPT,
    PLANNER_PROMPT,
    STORE_DECLINE_INSIGHT_PROMPT,
)
from backend.agents.state import AgentState, append_step, extract_json_block, extract_sql
from backend.analytics.store_decline import analyze_declining_stores
from backend.config import get_settings
from backend.data.db import run_query
from backend.data.schema import get_schema_text
from backend.tools.analytics_tools import get_date_context


def _invoke(system_prompt: str, user_content: str) -> str:
    llm = get_llm()
    response = llm.invoke(
        [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_content),
        ]
    )
    return str(response.content)


def orchestrator_node(state: AgentState) -> dict[str, Any]:
    output = _invoke(
        ORCHESTRATOR_PROMPT,
        f"User question:\n{state['question']}\n\nDate context:\n{state['date_context']}",
    )
    parsed = extract_json_block(output)
    return {
        "orchestration": json.dumps(parsed, indent=2),
        "steps": append_step("Orchestrator", "Classify question", json.dumps(parsed, indent=2)),
    }


def route_after_orchestrator(state: AgentState) -> Literal["store_decline_path", "standard_path"]:
    try:
        parsed = extract_json_block(state["orchestration"])
        if parsed.get("intent") == "store_decline_diagnosis":
            return "store_decline_path"
    except ValueError:
        question = state["question"].lower()
        if "declin" in question and "store" in question:
            return "store_decline_path"
    return "standard_path"


def store_decline_node(state: AgentState) -> dict[str, Any]:
    results = analyze_declining_stores()
    preview = json.dumps(results[:5], default=str, indent=2)
    return {
        "query_result": results,
        "sql": "-- store decline diagnostics generated by analytics module",
        "plan": json.dumps(
            {
                "metrics": ["monthly revenue trend", "channel mix", "promo usage", "performance factor"],
                "tables": ["v_orders_enriched", "store_master"],
                "steps": [
                    "Find stores with 2+ declining months in last 3 months",
                    "Attach channel shift, promo usage, and performance context",
                ],
            },
            indent=2,
        ),
        "steps": append_step(
            "Data Analyst",
            "Run store decline diagnostics",
            f"Found {len(results)} declining store(s).\nPreview:\n{preview}",
        ),
    }


def store_decline_insight_node(state: AgentState) -> dict[str, Any]:
    result_preview = json.dumps(state.get("query_result", []), default=str, indent=2)
    output = _invoke(
        STORE_DECLINE_INSIGHT_PROMPT,
        f"User question:\n{state['question']}\n\nDecline diagnostics:\n{result_preview}",
    )
    return {
        "answer": output.strip(),
        "steps": append_step("Insight Writer", "Write store decline insight", output.strip()),
    }


def planner_node(state: AgentState) -> dict[str, Any]:
    output = _invoke(
        PLANNER_PROMPT,
        (
            f"User question:\n{state['question']}\n\n"
            f"Orchestrator output:\n{state['orchestration']}\n\n"
            f"Date context:\n{state['date_context']}\n\n"
            f"Schema:\n{get_schema_text()}"
        ),
    )
    parsed = extract_json_block(output)
    return {
        "plan": json.dumps(parsed, indent=2),
        "steps": append_step("Query Planner", "Create analysis plan", json.dumps(parsed, indent=2)),
    }


def analyst_node(state: AgentState) -> dict[str, Any]:
    retry_note = ""
    if state.get("sql_error"):
        retry_note = (
            f"\nPrevious SQL:\n{state['sql']}\n\n"
            f"Error:\n{state['sql_error']}\n\nFix the query."
        )

    output = _invoke(
        ANALYST_PROMPT,
        (
            f"User question:\n{state['question']}\n\n"
            f"Plan:\n{state['plan']}\n\n"
            f"Date context:\n{state['date_context']}\n\n"
            f"Schema:\n{get_schema_text()}"
            f"{retry_note}"
        ),
    )
    sql = extract_sql(output)
    return {
        "sql": sql,
        "steps": append_step("Data Analyst", "Generate SQL", sql),
    }


def execute_sql_node(state: AgentState) -> dict[str, Any]:
    settings = get_settings()
    try:
        rows = run_query(state["sql"])
        if len(rows) > settings.max_query_rows:
            rows = rows[: settings.max_query_rows]
        preview = json.dumps(rows[:10], default=str, indent=2)
        return {
            "query_result": rows,
            "sql_error": "",
            "steps": append_step(
                "Data Analyst",
                "Execute SQL",
                f"Returned {len(rows)} row(s).\nPreview:\n{preview}",
            ),
        }
    except Exception as exc:
        return {
            "query_result": [],
            "sql_error": str(exc),
            "retry_count": state.get("retry_count", 0) + 1,
            "steps": append_step("Data Analyst", "Execute SQL", f"Error: {exc}"),
        }


def insight_node(state: AgentState) -> dict[str, Any]:
    result_preview = json.dumps(state.get("query_result", [])[:20], default=str, indent=2)
    if state.get("sql_error") and not state.get("query_result"):
        answer = (
            "I couldn't compute a reliable answer because the SQL query failed after retries. "
            f"Last error: {state['sql_error']}"
        )
        return {
            "answer": answer,
            "steps": append_step("Insight Writer", "Write response", answer),
        }

    output = _invoke(
        INSIGHT_PROMPT,
        (
            f"User question:\n{state['question']}\n\n"
            f"Analysis plan:\n{state['plan']}\n\n"
            f"Query results:\n{result_preview}"
        ),
    )
    return {
        "answer": output.strip(),
        "steps": append_step("Insight Writer", "Write business insight", output.strip()),
    }


def route_after_execute(state: AgentState) -> Literal["retry_analyst", "write_insight"]:
    settings = get_settings()
    if state.get("sql_error") and state.get("retry_count", 0) < settings.max_sql_retries:
        return "retry_analyst"
    return "write_insight"


def build_graph():
    graph = StateGraph(AgentState)

    graph.add_node("orchestrator", orchestrator_node)
    graph.add_node("store_decline", store_decline_node)
    graph.add_node("store_decline_insight", store_decline_insight_node)
    graph.add_node("planner", planner_node)
    graph.add_node("analyst", analyst_node)
    graph.add_node("execute_sql", execute_sql_node)
    graph.add_node("insight", insight_node)

    graph.set_entry_point("orchestrator")
    graph.add_conditional_edges(
        "orchestrator",
        route_after_orchestrator,
        {
            "store_decline_path": "store_decline",
            "standard_path": "planner",
        },
    )
    graph.add_edge("store_decline", "store_decline_insight")
    graph.add_edge("store_decline_insight", END)
    graph.add_edge("planner", "analyst")
    graph.add_edge("analyst", "execute_sql")
    graph.add_conditional_edges(
        "execute_sql",
        route_after_execute,
        {
            "retry_analyst": "analyst",
            "write_insight": "insight",
        },
    )
    graph.add_edge("insight", END)

    return graph.compile()


def run_analytics_question(question: str) -> dict[str, Any]:
    """Run the full agent workflow for a business question."""
    date_context = get_date_context.invoke({})
    app = build_graph()
    final_state = app.invoke(
        {
            "question": question,
            "date_context": date_context,
            "orchestration": "",
            "plan": "",
            "sql": "",
            "query_result": [],
            "sql_error": "",
            "retry_count": 0,
            "answer": "",
            "steps": [],
        }
    )
    return {
        "question": question,
        "answer": final_state.get("answer", ""),
        "sql": final_state.get("sql", ""),
        "data": final_state.get("query_result", []),
        "steps": final_state.get("steps", []),
        "plan": final_state.get("plan", ""),
        "orchestration": final_state.get("orchestration", ""),
    }
